version: '3.9'
services:
  box:
    image: devdotnetorg/alpine-ssh
    ports:
      - "2222:22"
    environment:
      - PSWD=123456
    networks:
      - elastic-service-network
    # volumes:
    #   - volume1:/root/a/:rw
    #   - volume2:/root/b/:rw
    #   - volume3:/root/c/:rw
      
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2m1"

  elastic_node_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elastic_node_1
    # ports:
    #   - "9201:9200"
    #   - "9301:9300"
    environment:
      - cluster.name=clustername
      - xpack.security.enabled=false
      - node.name=elastic_node_1
      # - discovery.seed_hosts=elastic_node_2:9300,elastic_node_3:9300
      - discovery.seed_hosts=elastic_node_1,elastic_node_2,elastic_node_3
      - cluster.initial_master_nodes=elastic_node_1,elastic_node_2,elastic_node_3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - network.publish_host=elastic_node_1
      # - network.host=_eth0_
      # - transport.port=9301
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2m1"
    networks:
      elastic-network:
        aliases:
          - elastic_node_1

  elastic_node_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elastic_node_2
    # ports:
    #   - "9202:9200"
    #   - "9302:9300"
    environment:
      - cluster.name=clustername
      - xpack.security.enabled=false
      - node.name=elastic_node_2
      # - discovery.seed_hosts=elastic_node_1:9300,elastic_node_3:9300
      - discovery.seed_hosts=elastic_node_1,elastic_node_2,elastic_node_3
      - cluster.initial_master_nodes=elastic_node_1,elastic_node_2,elastic_node_3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - network.publish_host=elastic_node_2
      # - network.host=_eth0_
      # - transport.port=9302
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2w1"
    networks:
      elastic-network:
        aliases:
          - elastic_node_2

  elastic_node_3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elastic_node_3
    # ports:
    #   - "9203:9200"
    #   - "9303:9300"
    environment:
      - cluster.name=clustername
      - xpack.security.enabled=false
      - node.name=elastic_node_3
      # - discovery.seed_hosts=elastic_node_1:9300,elastic_node_2:9300
      - discovery.seed_hosts=elastic_node_1,elastic_node_2,elastic_node_3      
      - cluster.initial_master_nodes=elastic_node_1,elastic_node_2,elastic_node_3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - network.publish_host=elastic_node_3
      # - network.host=_eth0_
      # - transport.port=9303
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2w2"
    networks:
      elastic-network:
        aliases:
          - elastic_node_3

# apache1:
  #   image: httpd:latest
  #   hostname: apache1
  #   volumes:
  #     - volume1:/usr/local/apache2/htdocs/:rw
  #   ports:
  #   - '8801:80'
  #   deploy:
  #     placement:
  #       constraints:
  #         - "node.hostname==testswac2w2"

networks:
  elastic-network:
    name: elastic-network
    attachable: true

# volumes:
#   volume1:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: nfsvers=4,addr=172.16.5.30,rw,proto=tcp,sec=sys,local_lock=none
#       device: ":/volume1/ELASTIC/test/data01"
#   volume2:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: nfsvers=4,addr=172.16.5.30,rw,proto=tcp,sec=sys,local_lock=none
#       device: ":/volume1/ELASTIC/test/data02"
#   volume3:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: nfsvers=4,addr=172.16.5.30,rw,proto=tcp,sec=sys,local_lock=none
#       device: ":/volume1/ELASTIC/test/data03"      