version: '3.9'                                                                                                                                                                                                      
services:                                                                                                                                                                                                           
  apache1:                                                                                                                                                                                                          
    image: httpd:latest                                                                                                                                                                                             
    hostname: apache1                                                                                                                                                                                               
    volumes:                                                                                                                                                                                                        
      - volume1:/usr/local/apache2/htdocs/:rw                                                                                                                                                                       
    ports:                                                                                                                                                                                                          
    - '8801:80'
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2w2"

  elastic2:                                                                                                                                                                                                          
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1                                                                                                                                                                                             
    hostname: elastic2                                                                                                                                                                                               
    ports:                                                                                                                                                                                                          
    - '9200:9200'
    environment:
      - cluster.name=clustername
      - xpack.security.enabled=false
      - node.name=elastic_node_2
      - discovery.seed_hosts=testswac2w1
      - cluster.initial_master_nodes=testswac2w1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2w1"

  apache3:                                                                                                                                                                                                          
    image: httpd:latest                                                                                                                                                                                             
    hostname: apache3                                                                                                                                                                                               
    ports:                                                                                                                                                                                                          
    - '8803:80'
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2m1"                                                                                                                                                                                                  
                                                                                                                                                                                                                    
volumes:                                                                                                                                                                                                            
  volume1:                                                                                                                                                                                                          
    driver: local                                                                                                                                                                                                   
    driver_opts:                                                                                                                                                                                                    
      type: nfs                                                                                                                                                                                                     
      o: nfsvers=4,addr=172.16.5.30,rw,proto=tcp,sec=sys,local_lock=none                                                                                                                                            
      device: ":/volume1/ELASTIC/test/data01"                                  
