version: '3.9'
services:
  # box:
  #   image: devdotnetorg/alpine-ssh
  #   ports:
  #     - "2222:22"
  #   environment:
  #     - PSWD=123456
  #   networks:
  #     - elastic-network
  #   volumes:
  #     - volume1:/root/a/:r
  #   #   - volume_2:/root/b/:rw
  #   #   - volume_3:/root/c/:rw
      
  #   deploy:
  #     placement:
  #       constraints:
  #         - "node.hostname==testswac2m1"

  # apache1:
  #   image: httpd:latest
  #   hostname: apache1
  #   ports:
  #   - '8888:80'
  #   deploy:
  #     placement:
  #       constraints:
  #         - "node.hostname==testswac2m1"
  elastic_node_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elastic_node_1
    # ports:
    #   - "9201:9200"
    #   - "9301:9300"
    env_file:
      - ./common.env
    environment:
      - node.name=elastic_node_1
      # - cluster.initial_master_nodes=elastic_node_1,elastic_node_2,elastic_node_3
      # - network.host=_eth0_
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2m1"
    volumes:
    - volume_1:/usr/share/elasticsearch/data:rw
    networks:
      elastic-network:
        aliases:
          - elastic_node_1

  elastic_node_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elastic_node_2
    # ports:
    #   - "9202:9200"
    #   - "9302:9300"
    env_file:
      - ./common.env
    environment:
      - node.name=elastic_node_2
      # - cluster.initial_master_nodes=elastic_node_1,elastic_node_2,elastic_node_3
      # - network.host=_eth0_

    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2w1"
    volumes:
    - volume_2:/usr/share/elasticsearch/data:rw    
    networks:
      elastic-network:
        aliases:
          - elastic_node_2

  elastic_node_3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elastic_node_3
    # ports:
    #   - "9203:9200"
    #   - "9303:9300"
    env_file:
      - ./common.env
    environment:
      - node.name=elastic_node_3
      # - cluster.initial_master_nodes=elastic_node_1,elastic_node_2,elastic_node_3
      # - network.host=_eth0_
      # - transport.port=9303
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - "node.hostname==testswac2w2"
    volumes:
    - volume_3:/usr/share/elasticsearch/data:rw    
    networks:
      elastic-network:
        aliases:
          - elastic_node_3

networks:
  elastic-network:
    name: elastic-network
    attachable: true
    ipam: 
      config:
        - subnet: 10.1.99.0/24

volumes:
  volume_1:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=172.16.5.30,rw,proto=tcp,sec=sys,local_lock=none
      device: ":/volume1/ELASTIC/test/data01"
  volume_2:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=172.16.5.30,rw,proto=tcp,sec=sys,local_lock=none
      device: ":/volume1/ELASTIC/test/data02"
  volume_3:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=172.16.5.30,rw,proto=tcp,sec=sys,local_lock=none
      device: ":/volume1/ELASTIC/test/data03"      